### ISSUE TITLE
Multiple groups

### ISSUE THREAD

**Issue by bbockelm** [gganis/vomsxrd#1]
Would it be possible to add a new grpopt in order to utilize _all_ groups?

The authdb format in xrootd understands multiple groups and I don't want to have to explicitly list all the leaf-groups in that file.

**Comment by gganis** [comment]
It should be possible. I'll have a look and let you know.

**Comment by bbockelm** [comment]
I do something similar for my HTTP security attribute extractor: https://github.com/bbockelm/xrootd-lcmaps/blob/master/src/XrdLcmapsKey.cc#L49

This allows me to have lines like this in the authfile for HTTP access:

```
g /cms /store
g /vo1 /user/vo1
g /vo2 /path/my-vo
```

Without having all group names listed in the entity, I needed a line per CMS group.

**Comment by gganis** [comment]
Hi Brian,

  Just to make sure, you would like the ‘all’ option to save all the groups, blank-separated, into the entity grps field, so that XrdAccAccess
  can loop on them, right?

**Comment by bbockelm** [comment]
Correct!

**Comment by gganis** [comment]
```
Hi Brian,

I have implemented group/which selection option ‘2’ which should do what you asked for.
I have created a test RPM for SL6

    /afs/cern.ch/work/g/ganis/public/vomsxrd/RPMS/vomsxrd-0.4.0-1.el6.x86_64.rpm

   (compiled with gcc 4.4 against xrootd 4.2.3)

or you can take the master at

   https://github.com/gganis/vomsxrd

To use the new option you have to set

        grpopt=2 or grpopt=12

Let me know,

Gerri
```

**Comment by bbockelm** [comment]
@djw8605 could you test this out on `red-test`?  This should allow us to simplify our plugin sequence (and no longer have to explicitly list all our VOMS groups!).

If it works, let's ask OSG to pull in the update.

**Comment by bbockelm** [comment]
@gganis - can I get you to tag the release?  I don't see the tags listed in github.

**Comment by gganis** [comment]
Sorry, it should be ok now.

**Comment by gganis** [comment]
Hi Brian,
Can I consider this solved?
Thanks,
Gerri

**Comment by bbockelm** [comment]
Yup, feel free to close!

**Comment by gganis** [comment]
Thanks!
